config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  namespace :lister do
    resources :bookings
    # equivalent to => get ‘/lister/bookings’, to: ‘lister/bookings#index’
    resources :surpluses
  end
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :surpluses, only: %i[index show new create] do
    resources :bookings, only: %i[create update]
  end
  resources :bookings, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :surplus

  enum status: %i[pending accepted rejected]
  validates :status, inclusion: { in: statuses.keys }
  validates :status, presence: true
end

app/models/surplus.rb
class Surplus < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_by_name_and_location_and_quantity,
                  against: %i[name location quantity],
                  using: {
                    tsearch: { prefix: true }
                  }
  belongs_to :user
  has_one_attached :photo
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  validates :category, :description, :quantity, :name, :location, presence: true
  validates :quantity, numericality: { only_integer: true }, inclusion: { in: 1..200, allow_nil: false }
  enum category: %i[bakery restaurant individual ngo butcher]
  validates :category, inclusion: { in: categories.keys }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :surpluses, through: :bookings
  enum category: %i[cafe ngo individual]

  def lister?
    self.surpluses.any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = policy_scope([:lister, Booking]).order(created_at: :desc)
  end

  def create
    @surplus = Surplus.find(params[:surplus_id])
    @booking = Booking.new(booking_params)
    @booking.surplus = @surplus
    @booking.user = current_user
    @booking.status = 'pending'
    if @booking.save
      redirect_to bookings_path
    else
      render 'surpluses/show'
    end
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to bookings_path

    else
      render 'bookings/index'# where was the booking update form?
    end
  end

  private

  def booking_params
    # TODO: check your model, might be different than mine
    params.require(:booking).permit(:date, :status)
  end
end

app/controllers/lister/bookings_controller.rb
class Lister::BookingsController < ApplicationController
  before_action :find_bookings, only: %i[show]

  def index
    @bookings = policy_scope [:lister, Booking]
  end

  def update
    @booking = Booking.find(params[:id])
    authorize [:lister, @booking]
    if @booking.update(booking_params)
      # redirect_to # up to you...
    else
      # render # where was the booking update form?
    end
  end

  def show

  end


  private

  def find_bookings
    @bookings.where(user_id params[user_id])
  end

  def booking_params
    # TODO: check your model, might be different than mine
    params.require(:booking).permit(:status)
  end
end

app/controllers/lister/surpluses_controller.rb
class Lister::SurplusesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/surpluses_controller.rb
class SurplusesController < ApplicationController
  before_action :find_surplus, only: %i[show edit]

  def index
    @surpluses = policy_scope(Surplus).order(created_at: :desc)
    if params[:category].present?
      @surpluses = @surpluses.includes(:user).where(user: { category: User.categories[params[:category]]})
    end
    if params[:query].present?
      @surpluses = Surplus.search_by_name_and_location_and_quantity(params[:query])

    end
    @count = @surpluses.count

    @markers = @surpluses.geocoded.map do |surplus|
      {
        lat: surplus.latitude,
        lng: surplus.longitude
      }
    end
  end

  def show
    @markers = [
      lat: @surplus.latitude,
      lng: @surplus.longitude
    ]
    @booking = Booking.new
    authorize @surplus
  end

  def edit; end

  def new
    @surplus = Surplus.new
    authorize @surplus
  end

  def create
    @surplus = Surplus.new(surplus_params)
    @surplus.user = current_user
    authorize @surplus

    if @surplus.save
      redirect_to surplus_path(@surplus)
    else
      render :new
    end
  end

  private

  def find_surplus
    @surplus = Surplus.find(params[:id])
  end

  def surplus_params
    params.require(:surplus).permit(:photo, :category, :description, :location, :quantity, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>My Bookings</h1>

    <% @bookings.each do |booking| %>
      <div class="container">
      <div class="row g-0">
      <div class="card-product">
        <img src= <%= cl_image_path booking.surplus.photo.key, height: 300, crop: :fill %>>
          <div class="card-product-infos">
        <%# <h2> <%= link_to booking.surplus.category, surplus_path(surplus) %>
          <div class="col-6 flex-grow">
            <div> <h2>Surplus </h2>
            <p><%= booking.surplus.description %></p></div>
          </div>
          <div class="col">
            <div><h2>Pick Up Date</h2>
            <p> <%= booking.date.strftime("%F")  %> </p></div>
          </div>
          <div class="col">
            <div><h2>Pick Up Time</h2>
            <p> <%= booking.date.strftime("%H:%M")  %> </p></div>
          </div>
          <div class="col">
            <div><h2>Status</h2>
              <% if booking.status == "accepted" %>
              <%# <button type="button" disabled class="btn btn-success"><%= booking.status %>
                <strong> <p style="color:green">  Accepted </p> </strong>
              <% elsif booking.status == "pending"%>
                <strong> <p style="color:orange">  Pending </p> </strong>
              <% else %>
                <strong> <p style="color:red">  Rejected </p> </strong>
              <% end %>
            </div>
          </div>
          </div>
      </div>
        </div>
      </div>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DONTTrashSoFast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/lister/bookings/index.html.erb
<div class="container">
  <div class="bookings">
    <% @bookings.order(created_at: :desc).each do |booking| %>
      <div class="booking d-flex flex-column-reverse">
        <div class='booking-left'>
          <div class="booking-info flex-column mb-3">
            <img src= <%= cl_image_path booking.surplus.photo.key, height: 300, crop: :fill %>>
            <div class="surplus-name">
              <%= booking.surplus.name %>
            </div>
            <div class="booking-info-title">
              <%= booking.user.email %>
            </div>
            <div class="booking-info-details">
              <%= booking.date.strftime("%F") %> - <%= booking.date.strftime("%H:%M") %>
            </div>
            <div class="booking-actions">
              <% if booking.pending? %>
                <%= simple_form_for(booking, url: lister_booking_path(booking), remote: true) do |f| %>
                  <%= f.input :status, as: :hidden, input_html: { value: 'accepted'} %>
                  <%= f.submit 'Accept', class: 'btn btn-info' %>
                <% end %>
                <%= simple_form_for(booking, url: lister_booking_path(booking)) do |f| %>
                  <%= f.input :status, as: :hidden, input_html: { value: 'rejected'} %>
                  <%= f.submit 'Reject', class: 'btn btn-light' %>
                <% end %>
              <% else %>
                <p class='booking-tag'><%= booking.status %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= image_path 'pineapples.jpg' %>)">
  <div class="container-home flex-column align-items-center">
    <div class="banner-text mb-3">
      <h1>Don't trash so fast! Bring <strong>down the carbon footprint </strong> for <strong> our dear planet</strong>!</h1>
      <p>Learn to make the most of leftovers that are still fresh and ready to eat.</p>
    </div>
    <%= form_tag surpluses_path, method: :get do %>
    <div class="search-form-home-control form-group mt-5">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control string required",
        placeholder: "Find local leftovers",
        data: { controller: 'search' }
      %>
      <%= submit_tag "Submit", class: "btn btn-ghost" %>
    </div>
    <% end %>
  </div>
</div>


<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path 'avocado.jpg' %>)">
    <%= link_to "Cafes", surpluses_path(category: 'cafe')%>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path 'steak.jpg' %>)">
    <%= link_to "NGOs", surpluses_path(category: 'ngo') %>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path 'schnitzel.jpg' %>)">
    <%= link_to "Individuals", surpluses_path(category: 'individual') %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to 'Create a new surplus', new_surplus_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Surpluses", surpluses_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <% if user_signed_in? && current_user.lister? %>
            <%= link_to 'Accept/Reject', lister_bookings_path, class: "nav-link" %>
          <% end %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "profile.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Reserved surpluses", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_surplus_index_card.html.erb
<div class="cards">
  <% @surpluses.each do |surplus| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path surplus.photo.key, height: 300, crop: :fill %> ')">
      <div class="card-category-banner">
        <div class="card-quantity">
          Qty. <%= surplus.quantity %>
        </div>
        <div class="card-location">
          <%= surplus.location.split(',').first %>
        </div>
      </div>
      <%= link_to surplus.name, surplus_path(surplus) %>
    </div>
  <% end %>
</div>

app/views/shared/_surplus_show_card.html.erb
<div class="position-relative">
  <h4 class="card-header"><%=  @surplus.location %></h4>
  <div class="card-category-show card-large">
    <div style="width: 500px; height: 600px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
      <div class="card-body">
        <h4 class="card-title"> <%= image_tag "storefront.svg" %> <%= @surplus.category %></h4>
        <h4 class="card-name"><%=  @surplus.name %> (Qty. <%= @surplus.quantity.to_s %>) </h4>
        <img src="<%= cl_image_path(@surplus.photo.key, width: 300, height: 300, crop: :fill) %>" alt="<%= @surplus.name %>" class="m-3">
        <div class="date-section">
          <p class="card-text"><%=  @surplus.description %></p>
          <h6>Pick up date and time</h6>
          <%= simple_form_for [@surplus, @booking] do |f| %>
            <%= f.input :date, label: false, html5: true %>
            <%= f.submit class: 'btn btn-success' %>
             <%= link_to 'Go Back', surpluses_path, class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/surpluses/_form.html.erb
<%= simple_form_for @surplus, url: surpluses_path do |f| %>
  <%= f.input :photo, as: :file %>
  <%= f.input :name, label: false, placeholder: "Bread" %>
  <%= f.input :category, label: "Group or individual?", collection: ["bakery", "butcher", "individual", "ngo", "restaurant"]%>
  <%= f.input :description, label: false, placeholder: "Overbought bread this month" %>
  <%= f.input :location,
              label: false,
              input_html: { data: { geocoder_target: "location" }, class: "d-none" },
              wrapper_html: { data: { controller: "geocoder",
              geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } }
  %>
  <%= f.input :quantity, label: false, placeholder: "How many?" %>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/surpluses/edit.html.erb
<h1>Editing surplus</h1>

<%= render 'form' %>

<%# <%= link_to 'Show', surpluses_path(@surplus) %>
<%# <%= link_to 'Back', surpluses_path %> 

app/views/surpluses/index.html.erb
<div class="container">
  <%= form_tag surpluses_path, method: :get do %>
  <div class="search-form-control form-group mb-3">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control string required",
        placeholder: "Find local leftovers"
      %>
      <%= submit_tag "Search", class: "btn btn-ghost" %>
  </div>
  <% end %>
  <p>Results <%= @count %></p>
  <div class="content">
      <%=  render 'shared/surplus_index_card' %>
    <div class="mx-3">
      <div style="width: 500px; height: 500px;" class=index-map
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
    <div class="text-center my-4">
      <%= link_to 'Create a new surplus', new_surplus_path, class: "btn btn-success" %>
    </div>
</div>

app/views/surpluses/new.html.erb
<%# <div class="banner" style="background-image: url(https://source.unsplash.com/I6mx55jXOvM)">
  <div class="container">
  </div>
</div> %>

<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new surplus</h3>
          <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/surpluses/show.html.erb
<div class="container">
  <%= render 'shared/surplus_show_card' %>
</div>